### ISSUE TITLE
Every download fails

### ISSUE THREAD

**Issue by sarathkrishnan-007** [rojter-tech/pluradl.py#40]
Checked with multiple credentials. Everything works on the browser, but blocks me from downloading with pluradl.py. Error log as below

[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] plura-dl version 1.0.0b4
[debug] Git HEAD: 73f0c9a
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] cloud-devops-securing-paas-iaas-saas: Downloading JSON metadata
[pluralsight:course] cloud-devops-securing-paas-iaas-saas: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
  File "C:\MyDownloads\Video\checkPython\pluradl.py\plura_dl\extractor\common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\MyDownloads\Video\checkPython\pluradl.py\plura_dl\PluraDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

Something went wrong.
The download request for 'cloud-devops-securing-paas-iaas-saas' was forced to terminate.
Double check that https://app.pluralsight.com/library/courses/cloud-devops-securing-paas-iaas-saas
exists or that your subscription is valid for accessing its content.

**Comment by fortunewalla** [comment]
My experiences:
------------------
If a course is not downloaded properly or error during download.

1) Move the course folder/directory from 'failed' to 'inprogress' and try again after 1 hour.
2) If access error again - Account maybe be blocked.

The tool works perfectly. The website security is very sensitive to usage.

* Don't use the script and website at the same time.
* Don't use many instances of the script. Only one script run at a time.
* Keep a gap of at least 30-45min between each course download. 
* Spread your usage throughout the day.
* Better to complete a course on website and then after 1 hour use the script to download. This shows up as you are reviewing the course again.

All the best!

**Comment by j00v** [comment]
I'm having the same issue as sarathkrishnan-007 since yesterday. Looks like PS enforced captcha checks on all new sessions (tried with different accounts on different browsers & IP addresses). Now I need to complete the captcha to access any content in the browser, and in the cli surely it returns 403. Did anyone else encounter this issue and could share a workaround?

**Comment by shawn8888** [comment]
<HTTPError 403: 'Forbidden'>
I have this error and after changing my public IP, it works again!

**Comment by j00v** [comment]
> <HTTPError 403: 'Forbidden'>
> I have this error and after changing my public IP, it works again!

Thanks for the hint, works for me again when using a fresh IP. Any ideas if the flagged IPs are flagged forever?

**Comment by rojter-tech** [comment]
> > <HTTPError 403: 'Forbidden'>
> > I have this error and after changing my public IP, it works again!
> 
> Thanks for the hint, works for me again when using a fresh IP. Any ideas if the flagged IPs are flagged forever?

@j00v IP flagging is problaby not flagged forever. That would be a very bad practice if the security team at Pluralsight implemented such restrictions. Normally there is an upper limit of leasing time specificied in order of a couple of days at most. Thereafter your IP can be recycled anytime to someone else that were not responsible for what you did. Most people don't own static IP leases from their ISP. :)

**Comment by sgiannino** [comment]
Does anyone knows any work around? Got the same error

` Downloading subtitles is set to: on 

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] plura-dl version 1.0.0b4
[debug] Git HEAD: edd1e17
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-46-generic-x86_64-with-elementary-5.1.3-hera
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] getting-started-with-asynchronous-programming-dotnet: Downloading JSON metadata
[download] Downloading playlist: Getting Started with Asynchronous Programming in .NET
[pluralsight:course] playlist Getting Started with Asynchronous Programming in .NET: Collected 28 video ids (downloading 28 of them)
[download] Downloading video 1 of 28
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
  File "/home/simone/Downloads/pluradl.py/plura_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/simone/Downloads/pluradl.py/plura_dl/PluraDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
 `

**Comment by sarathkrishnan-007** [comment]
Hi,

I think I might have found the issue. If you have multiple connections, it'll start failing. I was initially downloading using 2 laptops and both  failed after a few hours of download. Now I'm downloading using just 1 laptop and it works fine.
If it still fails, restart your router/modem and it should work again.
If you're downloading using multiple laptops, use different public IP for each, or use your mobile connection for the 2nd laptop.
If it still fails, your account might have been blocked, so login and check the account section to confirm your account is still active before proceeding.
Hope this helps.
